export const FETCH_EPISODES_START = 'FETCH_EPISODES_START'
export const FETCH_EPISODES_SUCCESS = 'FETCH_EPISODES_SUCCESS'
export const FETCH_EPISODES_ERROR = 'FETCH_EPISODES_ERROR'
export const EPISODES_SET_INFO = 'EPISODES_SET_INFO'
export const FETCH_EPISODE_SUCCESS = 'FETCH_EPISODE_SUCCESS'
export const FETCH_CHARACTERS_BY_IDS_START = 'FETCH_CHARACTERS_BY_IDS_START'

export const FETCH_CHARACTERS_SUCCESS_HOME = 'HOME.FETCH_CHARACTERS_SUCCESS'

export const FETCH_CHARACTERS_SUCCESS_CHARACTERS_PAGE = 'CHARACTERS_PAGE.FETCH_CHARACTERS_SUCCESS'
export const FETCH_CHARACTERS_ERROR = 'FETCH_CHARACTERS_ERROR'
export const CHARACTERS_SET_INFO = 'CHARACTERS_SET_INFO'

export const FETCH_LOCATION_START = 'FETCH_LOCATION_START'
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS'
export const FETCH_LOCATIONS_ERROR = 'FETCH_LOCATIONS_ERROR'
export const LOCATIONS_SET_INFO = 'LOCATIONS_SET_INFO'
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS'
export const FETCH_CHARACTERS_SUCCESS_LOCATIONS = 'LOCATIONS.FETCH_CHARACTERS_SUCCESS'
